# For more understanding about communication between containers, look at
# https://docs.docker.com/compose/networking/
version: '3'
services:
  database:
    image: mongo
    ports: 
      - 27017:27017
  
  restapi:
    build: ./src
    volumes: 
      - ./src:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - database
