# For more understanding about communication between containers, look at
# https://docs.docker.com/compose/networking/
version: '3'
services:
  database:
    build: ./dockerfiles/database
    container_name: mymongo
    ports: 
      - 27017:27017
  
  restapi:
    build: ./dockerfiles/restapi
    container_name: mynode
    volumes: 
      - ./src:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - DEPLOY=0
    
