FROM mongo
COPY './data/english_sample.json' /usr/data/english_sample.json
COPY './data/chinese_sample.json' /usr/data/chinese_sample.json
COPY './data/english.json' /usr/data/english.json
COPY './data/chinese.json' /usr/data/chinese.json
